version: "3.2"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped # NOTE: for production use, you should use "always"
    networks:
      - mre
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    ports:
      - 3307:3306
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped # NOTE: for production use, you should use "always"
    networks:
      - mre
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
networks:
  mre:
    driver: bridge