version: "3.2"
services:
  # mysql:
  #   image: mysql:8
  #   container_name: mysql
  #   command: mysqld --sql_mode="ALLOW_INVALID_DATES" --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   networks:
  #     - mre
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   volumes:
  #     - $HOME/database/mysql:/var/lib/mysql
  #   ports:
  #     - 3306:3306

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped # NOTE: for production use, you should use "always"
    networks:
      - mre
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    volumes:
      - $HOME/database/mariadb:/var/lib/mysql
      - ./mariadb/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    ports:
      - 3306:3306
    
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped # NOTE: for production use, you should use "always"
    networks:
      - mre
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - $HOME/database/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped # NOTE: for production use, you should use "always"
    networks:
      - mre
    ports:
      - 6379:6379

volumes:
  mariadb:
  postgres:

networks:
  mre:
    external: true