version: '3.8'

services:
  mongodb:
    image: mongo:6.0.18-rc0-jammy
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    networks:
      - optima
    volumes:
      - $HOME/database/mongodb:/data/db

networks:
  optima:
    external: true