version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: optima
      RABBITMQ_DEFAULT_PASS: optima
    volumes:
      - $HOME/database/rabbitmq:/var/lib/rabbitmq
    networks:
      - optima

volumes:
  rabbitmq:

networks:
  optima:
    external: true