version: "3.2"
services:

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped # NOTE: for production use, you should use "always"
    networks:
      - mre
    ports:
      - 6379:6379

networks:
  mre:
    external: true