version: "3.2"
services:
  php:
    build: './php/'
    container_name: php
    networks:
      - mre
    volumes:
      - './src/:/var/www/html/'
      - './php/php.ini-development:/usr/local/etc/php/php.ini-development'
      - './php/php.ini-production:/usr/local/etc/php/php.ini-production'
  apache:
    build: './apache/'
    container_name: apache
    depends_on:
      - php
    networks:
      - mre
    ports:
      - "80:80"
    volumes:
      - './src/:/var/www/html/'

networks:
  mre:
    external: true

