version: "3.2"
services:
  postgres:
    image: postgres
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - mre
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 3308:5432
networks:
  mre:
    driver: bridge